[package]
name = "disemvowel-in-rust"
version = "1.0.0"
authors = ["Paul Friederichsen <floogulinc@gmail.com>", "Nic McPhee <mcphee@morris.umn.edu>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
